#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp', '1.2.0'
cookbook 'openssh', '1.1.0'
cookbook 'apt', '1.5.0'
cookbook 'yum', '1.0.0'
cookbook 'build-essential', '1.1.2'
cookbook 'erlang', '1.1.0'
cookbook 'openssl', '1.0.0'
cookbook 'postgresql', '1.0.0'
cookbook 'aws', '0.100.2'
cookbook 'xfs', '1.0.0'
cookbook 'database', '1.3.6'
cookbook 'mysql', '1.3.0'
cookbook 'rabbitmq', '1.6.4'
cookbook 'apache2', '1.2.0'
cookbook 'selinux', '0.5.2'

cookbook 'sysctl',
  :git => 'https://github.com/mattray/sysctl.git'

cookbook 'osops-utils',
  :git => 'https://github.com/cloudbau/chef-osops-utils.git'

cookbook 'rabbitmq-openstack',
  :git => 'https://github.com/mattray/rabbitmq-openstack.git'

cookbook 'mysql-openstack',
  :git => 'https://github.com/mattray/mysql-openstack.git'

cookbook 'keystone',
  :git => 'https://github.com/cloudbau/chef-keystone.git'

cookbook 'glance',
  :git => 'https://github.com/djoreilly/chef-glance.git'

cookbook 'nova',
  :git => 'https://github.com/djoreilly/chef-nova.git'

cookbook 'horizon',
  :git => 'https://github.com/cloudbau/chef-horizon.git'

# cookbook 'swift',
#   :git => 'https://github.com/mattray/swift.git',
#   :ref => 'essex'
